#include "pch.h"
#include "WavReader.h"
#include "cpu/SignalForge.h"
#include <filesystem>
#include "TestHelpers.h"


namespace SignalForge {
    // ================================================================================
    // SHA256Tests - Small synthetic buffers (kept as baseline)
    // ================================================================================
    TEST(SHA256Tests, AllZeros_64bytes)
    {
        uint8_t  h_input[64] = { 0 };
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 64, h_hash);
        EXPECT_EQ(h_hash[0], 0xF5A5FD42D16A2030ULL);
        EXPECT_EQ(h_hash[1], 0x2798EF6ED309979BULL);
        EXPECT_EQ(h_hash[2], 0x43003D2320D9F0E8ULL);
        EXPECT_EQ(h_hash[3], 0xEA9831A92759FB4BULL);
    }

    TEST(SHA256Tests, AllZeros_256bytes)
    {
        uint8_t  h_input[256] = { 0 };
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 256, h_hash);
        EXPECT_EQ(h_hash[0], 0x5341E6B2646979A7ULL);
        EXPECT_EQ(h_hash[1], 0x0E57653007A1F310ULL);
        EXPECT_EQ(h_hash[2], 0x169421EC9BDD9F1AULL);
        EXPECT_EQ(h_hash[3], 0x5648F75ADE005AF1ULL);
    }

    TEST(SHA256Tests, AllZeros_1024bytes)
    {
        uint8_t  h_input[1024] = { 0 };
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 1024, h_hash);
        EXPECT_EQ(h_hash[0], 0x5F70BF18A0860070ULL);
        EXPECT_EQ(h_hash[1], 0x16E948B04AED3B82ULL);
        EXPECT_EQ(h_hash[2], 0x103A36BEA41755B6ULL);
        EXPECT_EQ(h_hash[3], 0xCDDFAF10ACE3C6EFULL);
    }

    TEST(SHA256Tests, Sequential_1024bytes)
    {
        uint8_t h_input[1024];
        for (int i = 0; i < 1024; i++)
            h_input[i] = i % 256;
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 1024, h_hash);
        EXPECT_EQ(h_hash[0], 0x785B0751FC2C53DCULL);
        EXPECT_EQ(h_hash[1], 0x14A4CE3D800E69EFULL);
        EXPECT_EQ(h_hash[2], 0x9CE1009EB327CCF4ULL);
        EXPECT_EQ(h_hash[3], 0x58AFE09C242C26C9ULL);
    }

    TEST(SHA256Tests, Alternating_1024bytes)
    {
        uint8_t h_input[1024];
        for (int i = 0; i < 1024; i++)
            h_input[i] = (i % 2 == 0) ? 0xAA : 0x55;
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 1024, h_hash);
        EXPECT_EQ(h_hash[0], 0xD4576A496A9C3150ULL);
        EXPECT_EQ(h_hash[1], 0x3534882C0B7D4CC8ULL);
        EXPECT_EQ(h_hash[2], 0x2AFBCC67D59E8A34ULL);
        EXPECT_EQ(h_hash[3], 0x85EED782B653AE7FULL);
    }

    TEST(SHA256Tests, AllFF_1024bytes)
    {
        uint8_t h_input[1024];
        memset(h_input, 0xFF, 1024);
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(h_input, 1024, h_hash);
        EXPECT_EQ(h_hash[0], 0x5F4ECDB7B71C3E40ULL);
        EXPECT_EQ(h_hash[1], 0x3983FE405CDDCDC2ULL);
        EXPECT_EQ(h_hash[2], 0xF2576B655FDB3E80ULL);
        EXPECT_EQ(h_hash[3], 0xD94A6F7C32E58BC2ULL);
    }

    // ================================================================================
    // SHA256Tests - Real WAV files (medium size, SignalForge target range)
    // Hashes generated by generate_signals.py (PCM data only, skipping WAV header)
    // ================================================================================

    // --- Clean signals (deterministic, both files must produce identical hashes) ---
    TEST(SHA256Tests, CleanSignal_500kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_500kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0x9F0148E8D4556E5CULL);
        EXPECT_EQ(h_hash[1], 0xD1FED78881D28D86ULL);
        EXPECT_EQ(h_hash[2], 0x160AE9606B57129AULL);
        EXPECT_EQ(h_hash[3], 0x2B5726D536D3701EULL);
    }

    TEST(SHA256Tests, CleanSignal_500kb_BothFilesMatch)
    {
        uint64_t h_hash_a[4] = { 0, 0, 0, 0 };
        uint64_t h_hash_b[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_500kb_001.wav"), h_hash_a);
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_500kb_002.wav"), h_hash_b);
        EXPECT_EQ(h_hash_a[0], h_hash_b[0]);
        EXPECT_EQ(h_hash_a[1], h_hash_b[1]);
        EXPECT_EQ(h_hash_a[2], h_hash_b[2]);
        EXPECT_EQ(h_hash_a[3], h_hash_b[3]);
    }

    TEST(SHA256Tests, CleanSignal_1024kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_1024kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0xA1B34DADE37A9E14ULL);
        EXPECT_EQ(h_hash[1], 0x622BC08DA1FF5330ULL);
        EXPECT_EQ(h_hash[2], 0xA994EF470F66C8A6ULL);
        EXPECT_EQ(h_hash[3], 0x086C21BA8C69FD0AULL);
    }

    TEST(SHA256Tests, CleanSignal_1024kb_BothFilesMatch)
    {
        uint64_t h_hash_a[4] = { 0, 0, 0, 0 };
        uint64_t h_hash_b[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_1024kb_001.wav"), h_hash_a);
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_1024kb_002.wav"), h_hash_b);
        EXPECT_EQ(h_hash_a[0], h_hash_b[0]);
        EXPECT_EQ(h_hash_a[1], h_hash_b[1]);
        EXPECT_EQ(h_hash_a[2], h_hash_b[2]);
        EXPECT_EQ(h_hash_a[3], h_hash_b[3]);
    }

    // --- Noisy signals (random noise, each file must produce a different hash) ---
    TEST(SHA256Tests, NoisySignal_500kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_noisy_500kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0xF9AF5D1AF380BA6CULL);
        EXPECT_EQ(h_hash[1], 0xC445A008A1DE8227ULL);
        EXPECT_EQ(h_hash[2], 0x4D127D8252486B6AULL);
        EXPECT_EQ(h_hash[3], 0xB6AA06CC513272E2ULL);
    }

    TEST(SHA256Tests, NoisySignal_500kb_FilesAreDifferent)
    {
        uint64_t h_hash_a[4] = { 0, 0, 0, 0 };
        uint64_t h_hash_b[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_noisy_500kb_001.wav"), h_hash_a);
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_noisy_500kb_002.wav"), h_hash_b);

        bool different =
            h_hash_a[0] != h_hash_b[0] || h_hash_a[1] != h_hash_b[1] ||
            h_hash_a[2] != h_hash_b[2] || h_hash_a[3] != h_hash_b[3];
        EXPECT_TRUE(different);
    }

    TEST(SHA256Tests, NoisySignal_1024kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_noisy_1024kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0x5729EDF3A35F9EE3ULL);
        EXPECT_EQ(h_hash[1], 0x54FBA78B4F1D3ABCULL);
        EXPECT_EQ(h_hash[2], 0x157B07ACBAD0DAB6ULL);
        EXPECT_EQ(h_hash[3], 0x340D76568C56DC79ULL);
    }

    // --- Anomaly signals ---
    TEST(SHA256Tests, AnomalySignal_500kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_anomaly_500kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0xBACAF320DD7876FAULL);
        EXPECT_EQ(h_hash[1], 0x330E13F4355C8A4AULL);
        EXPECT_EQ(h_hash[2], 0xEBF6461AA793D9B9ULL);
        EXPECT_EQ(h_hash[3], 0x820D214AE631E306ULL);
    }

    TEST(SHA256Tests, AnomalySignal_1024kb_KnownHash)
    {
        uint64_t h_hash[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_anomaly_1024kb_001.wav"), h_hash);
        EXPECT_EQ(h_hash[0], 0x302AC2C35E2F2812ULL);
        EXPECT_EQ(h_hash[1], 0xA12A45DB8D3385EAULL);
        EXPECT_EQ(h_hash[2], 0xF5586797B43A1AC2ULL);
        EXPECT_EQ(h_hash[3], 0x0D3F372978EDC130ULL);
    }

    // --- Cross-type: clean vs noisy must never match ---
    TEST(SHA256Tests, CleanAndNoisy_500kb_HashesAreDifferent)
    {
        uint64_t h_clean[4] = { 0, 0, 0, 0 };
        uint64_t h_noisy[4] = { 0, 0, 0, 0 };
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_clean_500kb_001.wav"), h_clean);
        TestHelpers::HashWavFile(TestHelpers::TestDataPath("engine_noisy_500kb_001.wav"), h_noisy);

        bool different =
            h_clean[0] != h_noisy[0] || h_clean[1] != h_noisy[1] ||
            h_clean[2] != h_noisy[2] || h_clean[3] != h_noisy[3];
        EXPECT_TRUE(different);
    }

    // ================================================================================
    // SHA256Tests - Batch hashing
    // ================================================================================
    TEST(SHA256Tests, DISABLED_BatchHash_MatchesSingleHash)
    {
        // Hash two files individually, then batch hash them, results must match
        SignalForge::WavReader reader_a(TestHelpers::TestDataPath("engine_clean_500kb_001.wav"));
        SignalForge::WavReader reader_b(TestHelpers::TestDataPath("engine_clean_1024kb_001.wav"));

        auto pcm_a = reader_a.ReadPCM();
        auto pcm_b = reader_b.ReadPCM();

        // Single hash
        uint64_t h_single_a[4] = { 0, 0, 0, 0 };
        uint64_t h_single_b[4] = { 0, 0, 0, 0 };
        SHA256HashWrapper_CPU(pcm_a.data(), pcm_a.size(), h_single_a);
        SHA256HashWrapper_CPU(pcm_b.data(), pcm_b.size(), h_single_b);

        // Batch hash
        std::vector<std::vector<uint8_t>> inputs = { pcm_a, pcm_b };
        uint64_t h_batch[8] = { 0 };
        SHA256BatchWrapper_CPU(inputs, h_batch, 2, 32);

        // Compare
        EXPECT_EQ(h_batch[0], h_single_a[0]);
        EXPECT_EQ(h_batch[1], h_single_a[1]);
        EXPECT_EQ(h_batch[2], h_single_a[2]);
        EXPECT_EQ(h_batch[3], h_single_a[3]);

        EXPECT_EQ(h_batch[4], h_single_b[0]);
        EXPECT_EQ(h_batch[5], h_single_b[1]);
        EXPECT_EQ(h_batch[6], h_single_b[2]);
        EXPECT_EQ(h_batch[7], h_single_b[3]);
    }

} // namespace SignalForge