// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SignalForge.proto

#include "SignalForge.pb.h"
#include "SignalForge.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace SignalForge {

static const char* SignalForgeService_method_names[] = {
  "/SignalForge.SignalForgeService/SendFile",
};

std::unique_ptr< SignalForgeService::Stub> SignalForgeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SignalForgeService::Stub> stub(new SignalForgeService::Stub(channel, options));
  return stub;
}

SignalForgeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendFile_(SignalForgeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SignalForgeService::Stub::SendFile(::grpc::ClientContext* context, const ::SignalForge::FileRequest& request, ::SignalForge::FileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SignalForge::FileRequest, ::SignalForge::FileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendFile_, context, request, response);
}

void SignalForgeService::Stub::async::SendFile(::grpc::ClientContext* context, const ::SignalForge::FileRequest* request, ::SignalForge::FileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SignalForge::FileRequest, ::SignalForge::FileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendFile_, context, request, response, std::move(f));
}

void SignalForgeService::Stub::async::SendFile(::grpc::ClientContext* context, const ::SignalForge::FileRequest* request, ::SignalForge::FileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SignalForge::FileResponse>* SignalForgeService::Stub::PrepareAsyncSendFileRaw(::grpc::ClientContext* context, const ::SignalForge::FileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SignalForge::FileResponse, ::SignalForge::FileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SignalForge::FileResponse>* SignalForgeService::Stub::AsyncSendFileRaw(::grpc::ClientContext* context, const ::SignalForge::FileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

SignalForgeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SignalForgeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SignalForgeService::Service, ::SignalForge::FileRequest, ::SignalForge::FileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SignalForgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SignalForge::FileRequest* req,
             ::SignalForge::FileResponse* resp) {
               return service->SendFile(ctx, req, resp);
             }, this)));
}

SignalForgeService::Service::~Service() {
}

::grpc::Status SignalForgeService::Service::SendFile(::grpc::ServerContext* context, const ::SignalForge::FileRequest* request, ::SignalForge::FileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SignalForge
#include <grpcpp/ports_undef.inc>

