syntax = "proto3";

package SignalForge;

service SignalForgeService {
    rpc SendFile    (FileRequest)      returns (FileResponse);
    rpc Register    (RegisterRequest)  returns (RegisterResponse);
    rpc Shutdown    (ShutdownRequest)  returns (ShutdownResponse);
}

message FileRequest {
    bytes data = 1;
}

message FileResponse {
    bool   accepted = 1;
    string message  = 2;
}

message RegisterRequest  {}

message RegisterResponse {
    bool   accepted  = 1;
    string client_id = 2;
}

message ShutdownRequest {
    string client_id = 1;
}

message ShutdownResponse {
    bool   accepted = 1;
    string message  = 2;
}