# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignalForge.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'SignalForge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SignalForge.proto\x12\x0bSignalForge\"\x1b\n\x0b\x46ileRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"1\n\x0c\x46ileResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x12SignalForgeService\x12?\n\x08SendFile\x12\x18.SignalForge.FileRequest\x1a\x19.SignalForge.FileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignalForge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=34
  _globals['_FILEREQUEST']._serialized_end=61
  _globals['_FILERESPONSE']._serialized_start=63
  _globals['_FILERESPONSE']._serialized_end=112
  _globals['_SIGNALFORGESERVICE']._serialized_start=114
  _globals['_SIGNALFORGESERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
